name: Our Called
on:
  workflow_call:
    inputs:
      env:
        type: string
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running in ${{ inputs.env }}"
