name: Our Reusable
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      notify:
        type: boolean
        default: false

jobs:
  deploy:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install
        run: echo "install"
      - name: Format
        run: echo "format"
      - name: Lint
        run: echo "lint"
      - name: Test
        run: echo "test"
      - name: Build
        run: echo "build"
      - name: Deploy
        run: echo "deploying in ${{ inputs.env }}"
  notify:
    if: inputs.notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: echo "deploying"
